services:
  - type: pserv
    name: mssql
    env: image
    image:
      url: mcr.microsoft.com/mssql/server:2017-latest
    plan: standard
    autoDeploy: false
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: MSSQL_SA_PASSWORD
        value: "YourStrong@Passw0rd"

#     disk:
#       name: data
#       mountPath: /var/lib/clickhouse
#       sizeGB: 10
